<?php
/**
 * @file
 * Provide a rotating item display style for Views.
 *
 * This is a placeholder file so drupal will enable the module. All logic is contained in
 * other files located with the module.
 */

/**
 * Implementation of hook_views_api().
 */
function views_galleria_views_api() {
  return array('api' => 2);
}

/**
 * Template function for views_galleria
 *
 * @param array $vars
 *  Array of template variables.
 */
function template_preprocess_views_view_galleria(&$vars) {
  drupal_add_css(drupal_get_path('module', 'views_galleria') .'/galleria.css');

  $view = $vars['view'];
  $options = $view->style_plugin->options;

  $vars['views_galleria_id'] = 'views-galleria-'. $view->name .'-'. $view->current_display;

  drupal_add_js(drupal_get_path('module', 'views_galleria') .'/jquery.galleria.js');
  drupal_add_js(drupal_get_path('module', 'views_galleria') .'/galleria_options.js');

  $view_settings['fx'] = 'fade';
  $view_settings['timeout'] = check_plain($options['timeout']) * 1000;
  $view_settings['speed'] = check_plain($options['speed']) * 1000;
  $view_settings['pause'] = check_plain($options['pause']);
  $view_settings['cleartype'] = 1;

  if (!empty($options['back_next_buttons'])) {
    $view_settings['next'] = '#'. $vars['views_galleria_id'] .'-views-rotator-next';
    $view_settings['prev'] = '#'. $vars['views_galleria_id'] .'-views-rotator-prev';
  }

  if (empty($options['height'])) {
    $view_settings['height'] = 'auto';
    $view_settings['auto_height'] = 1;
  }

  //drupal_add_js(array('views_galleria' => array($vars['views_galleria_id'] => $view_settings)), 'setting');
}

/**
 * Only returns true the first time it's called for an id
 *
 * @param $id
 *  A uniqe view id.
 *
 * @return bool
 *  TRUE for the first time called for a given $id
 *  FALSE for each time after that
 */
function theme_views_galleria_display_item($id) {
  static $display = array();

  if (!isset($display[$id])) $display[$id] = FALSE;

  $output = $display[$id];

  if ($display[$id] == FALSE) $display[$id] = TRUE;

  return $output;
}