<?php
// $Id: spamicide.module,v 1.3 2009/05/16 20:00:38 lipcpro Exp $

/**
 * @defgroup spamicide Spamicide: another tool to eliminate spam.
 *
 * The spamicide module provides the ability to prevent spam being submitted to your site on various drupal forms.
 * 
 * Author:  Wes Roepken aka lipcpro (wes@lipcpro.com)
 * Date:    04/13/2009
 */


/**
 * @file
 * This module provides yet another tool to eliminate spam.
 *
 * @ingroup spamicide
 */

function spamicide_menu() {
  $items = array();
  $items['admin/settings/spamicide'] = array(
    'title' => 'Spamicide',
    'description' => 'Administer how and where Spamicide is used.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spamicide_admin_form'),
    'access arguments' => array('administer spamicide'),
    'type' => MENU_NORMAL_ITEM,
  );
  // form for adding/editing spamicide form
  $items['admin/settings/spamicide/spamicide_form/add/%'] = array(
    'title' => 'Set Spamicide form',
    'description' => 'Add or edit form_id\'s to protect with Spamicide.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spamicide_admin_adform_form', 5, TRUE),
    'access arguments' => array('administer spamicide'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/spamicide/spamicide_form/delete/%'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spamicide_delete_confirm', 5, TRUE),
    'access arguments' => array('administer spamicide'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function spamicide_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/spamicide':
      return t('The spamicide module provides the ability to prevent spam being submitted to your site on various drupal forms');

    case 'admin/help#spamicide':
      $output = 'Spamicide';
      $output .= '<p>'. t("Spamicide is intended to prevent spam without user interaction. Select the forms you'd like to attach spamicide to and a form field will be added but hidden by css. If the field is filled by anything (including humans that think they know better) it will prevent submission into you site.") .'</p>';
      $output .= '<p>'. t('To add Spamicide to a form once you\'ve enabled adding admin links, navigate to that form, and click the link "Add Spamicide protection to this form"') .'</p>';
      return $output;
  }
}

function spamicide_perm() {
  return array('administer spamicide');
}


/**
 * Implementation of hook_theme().
 */
function spamicide_theme() {
  return array(
    'spamicide_admin_settings_spamicide' => array(
      'arguments' => array('form' => NULL)
    )
  );
}

/**
 * Form for spamicide administration
 * @param $spamicide_form_id
 * @return unknown_type
 */
function spamicide_admin_form($form) {
  $form = array();
  $form['spamicide_administration_mode'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add Spamicide administration links to forms'),
    '#default_value' => variable_get('spamicide_administration_mode', FALSE),
    '#description' => t('This option will allow enabling/disabling Spamicide on forms. When enabled, users with the "%adminspamicide" permission will see Spamicide administration links on all forms (except on administrative pages, which shouldn\'t be accessible to untrusted users in the first place). These links make it possible to enable or disable it for the desired type.', array('%adminspamicide' => t('administer Spamicide settings'))),
  );
  $form['spamicide_forms'] = array(
    '#type' => 'fieldset',
    '#title' => t('Add Spamicide to a form or remove an added form'),
    '#description' => t('Select from the listed forms (identified by their so called <em>form_id</em>\'s). You can easily add arbitrary forms with the help of the \'%spamicide_admin_links\' option or the <a href="!add_spamicide">the Spamicide form</a>.',
    array('%spamicide_admin_links' => t('Add Spamicide administration links to forms'),
    '!add_spamicide' => url('admin/settings/spamicide/add_form'))),
    '#tree' => TRUE,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#theme' => 'spamicide_admin_settings_spamicide',
  );
  // list all possible form_id's
  $result = db_query("SELECT * FROM {spamicide} ORDER BY form_id");
  while ($spamicide = db_fetch_object($result)) {
    $form['spamicide_forms'][$spamicide->form_id]['enabled'] = array(
      '#type' => 'checkbox',
      '#default_value' => $spamicide->enabled,
    );
    $form['spamicide_forms'][$spamicide->form_id]['form_id'] = array(
      '#value' => $spamicide->form_id,
    );
    $form['spamicide_forms'][$spamicide->form_id]['form_field'] = array(
      '#type' => 'textfield',
      '#size' => 30,
      '#default_value' => $spamicide->form_field,
    );
    // additional operations
    if ($spamicide->removable) {
      $form['spamicide_forms'][$spamicide->form_id]['operations'] = array(
        '#value' => implode(", ", array(
          l(t('delete'), "admin/settings/spamicide/spamicide_form/delete/{$spamicide->form_id}"),
        ))
      );
    }
    else {
      $form['spamicide_forms'][$spamicide->form_id]['operations'] = array(
        '#value' => "N/A",
      );
    }
  }
    $form['spamicide_log_attempts'] = array(
    '#type' => 'checkbox',
    '#title' => t('Log attempts'),
    '#description' => t('Report information about attempts to the !watchdoglog.', array('!watchdoglog' => l(t('log'), 'admin/reports/watchdog'))),
    '#default_value' => variable_get('spamicide_log_attempts', FALSE),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}


/**
 * Custom theme function
 * @param $form
 * @return unknown_type
 */
function theme_spamicide_admin_settings_spamicide($form) {
  foreach (element_children($form) as $key) {
    $row = array();
    $row[] = drupal_render($form[$key]['enabled']);
    $row[] = drupal_render($form[$key]['form_id']);
    $row[] = drupal_render($form[$key]['form_field']);
    $row[] = drupal_render($form[$key]['operations']);
    $rows[] = $row;
  }
  $header = array('Enabled', 'Form_id', 'Form field name', t('Delete'));
  $output = theme('table', $header, $rows);
  return $output;
}


function spamicide_admin_form_validate($form, &$form_state) {
  foreach ($form_state['values']['spamicide_forms'] as $spamicide_form_id => $data) {
    if (preg_match_all('[\W]', $data['form_field'], $str)) {
      form_set_error('spamicide_forms]['. $spamicide_form_id .'][form_field', t("Only AlphaNumeric characters or the underscore please"));
    }
  }
}

/**
 * Implementation of hook_form_submit
 * @param $form
 * @param $form_values
 */
function spamicide_admin_form_submit($form, &$form_state) {
    variable_set('spamicide_administration_mode', $form_state['values']['spamicide_administration_mode']);
    /*
     * need to implement admin links yet
     */
    foreach ($form_state['values']['spamicide_forms'] as $spamicide_form_id => $data) {
      if ($data['form_field'] != 'feed_me') {
        _spamicide_set_css_file($data['form_field']);
/*        $css_file = 'spamicide/'. $data['form_field'] .'.css';
        $path = file_create_path($css_file);
        if (!file_exists($path)) { // or !is_file or !file_exists or !file_check_location
          $css = "#edit-". str_replace('_', '-', $data['form_field']) ."-wrapper\n{\n  display: none;\n}\n";
          file_save_data($css, $css_file, FILE_EXISTS_REPLACE);
        }*/
      }
        db_query("UPDATE {spamicide} SET enabled = '%s', form_field = '%s' WHERE form_id = '%s'", $data['enabled'], $data['form_field'], $spamicide_form_id);
    }
    variable_set('spamicide_log_attempts', $form_state['values']['spamicide_log_attempts']);
    drupal_set_message(t('The Spamicide settings were saved.'), 'status');
}


/**
 * Form for adding spamicide functionality to an existing form
 * @param $spamicide_form_id
 * @return $form
 */
function spamicide_admin_adform_form($form, $spamicide_form_id=NULL) {
  $form = array();
  // use given spamicide form_id
  $form['spamicide_form_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Form ID'),
    '#description' => t('The Drupal form_id of the form to add the Spamicide to.'),
    '#value' => check_plain($spamicide_form_id),
    '#disabled' => TRUE,
  );
  $form['spamicide_form_field'] = array(
    '#type' => 'textfield',
    '#title' => t('Form field'),
    '#default_value' => 'feed_me',
    '#description' => t('The name you want for the field. Use only letters, numbers, and the underscore character(_).'),
  );
  // redirect to general Spamicide settings page after submission
  $form['#redirect'] = 'admin/settings/spamicide';
  // submit button
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}


/**
 * Implementation of hook_form_submit
 * @param $form
 * @param $form_values
 */
function spamicide_admin_adform_form_submit($form, &$form_state) {
  $spamicide_form_id = $form_state['values']['spamicide_form_id'];
  // remove old settings
  db_query("DELETE FROM {spamicide} WHERE form_id = '%s'", $spamicide_form_id);
  // save new settings
  db_query("INSERT INTO {spamicide} (form_id, form_field, enabled, removable) VALUES ('%s','%s', 1, 1)", $spamicide_form_id, $form_state['values']['spamicide_form_field']);
  _spamicide_set_css_file($form_state['values']['spamicide_form_field']);
  drupal_set_message(t('Saved Spamicide settings.'), 'status');
}


/**
 * Confirm dialog for disabling/deleting a Spamicide
 *
 * @param $spamicide_form_id the form_id of the form to delete the Spamicide
 *   from
 * @param $delete boolean for also deleting the Spamicide
 */
function spamicide_delete_confirm(&$form_state, $spamicide_form_id, $delete) {
  $form = array();
  $form['spamicide_form_id'] = array(
    '#type' => 'value',
    '#value' => $spamicide_form_id,
  );
  $form['spamicide_delete'] = array(
    '#type' => 'value',
    '#value' => $delete,
  );
    $message = t('Are you sure you want to delete the Spamicide for form_id %form_id?', array('%form_id' => $spamicide_form_id));
    $yes = t('Delete');
  return confirm_form($form, $message, isset($_GET['destination']) ? $_GET['destination'] : 'admin/settings/spamicide/spamicide_form', '', $yes);
}

/**
 * submission handler of Spamicide delete confirm_form
 */
function spamicide_delete_confirm_submit($form, &$form_state) {
  $spamicide_form_id = $form_state['values']['spamicide_form_id'];
  $delete = $form_state['values']['spamicide_delete'];
    db_query("DELETE FROM {spamicide} WHERE form_id = '%s'", $spamicide_form_id);
    drupal_set_message(t('Deleted Spamicide for form %form_id.', array('%form_id' => $spamicide_form_id)));
  // redirect to Spamicide admin
  $form_state['redirect'] =   'admin/settings/spamicide';
}


/**
 * Implementation of hook_form_alter
 * @param $form_id
 * @param $form
 */
function spamicide_form_alter(&$form, $form_state, $form_id) {
    $spamicide_field = _spamicide_get_field($form_id);
    if ($spamicide_field) {
        if ($spamicide_field == 'feed_me') {
          drupal_add_css(drupal_get_path('module', 'spamicide') .'/feed_me.css');
        }
        else {
          drupal_add_css(file_directory_path() .'/spamicide/'. $spamicide_field .'.css');
        }
        $spamicide_description = _spamicide_get_description();
        $form[$spamicide_field] = array(
          '#type' => 'textfield',
          '#size' => 20,
          '#description' => $spamicide_description,
        );
        $form['destination'] = array(
          '#type' => 'value',
          '#value' => drupal_get_destination(),
        );
        $form['#pre_render'][] = 'spamicide_pre_render_place_spamicide';
        $form['spamicide']['#validate']['spamicide_validate'] = array();
    }
    else if (user_access('administer spamicide') && variable_get('spamicide_administration_mode', TRUE) && arg(0) != 'admin') {
      $form['spamicide'] = array(
        '#type' => 'fieldset',
        '#title' => t('Spamicide'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );
      $form['spamicide']['add_spamicide'] = array(
        '#value' => l(t('Add Spamicide protection to this form.'), "admin/settings/spamicide/spamicide_form/add/$form_id", array()),
      );
      // Add pre_render function for placing the Spamicide just above the submit button
      $form['#pre_render'][] = 'spamicide_pre_render_place_spamicide';
    }
    else {
      return;
    }
}


/**
 * Implementation of hook_validate
 * @param $form_values
 * @return none
 */
function spamicide_validate($form, &$form_state) {
  $form_id = $form_state['values']['#post']['form_id'];
  $spamicide_field = _spamicide_get_field($form_id);
  if (!$spamicide_field) {
    return;
  }
  else if (empty($form_state['values']['#post'][$spamicide_field])) {
    return;
  }
  else {
    // update attempt counter
    variable_set('spamicide_attempt_counter', variable_get('spamicide_attempt_counter', 0) + 1);
    // log to watchdog if needed
    if (variable_get('spamicide_log_attempts', FALSE)) {
      watchdog('Spamicide',
        t('%form_id post blocked by Spamicide module: their IP address is "%ipaddress".',
          array('%form_id' => $form_id, '%ipaddress' => $_ENV['REMOTE_ADDR'])
        ),
        WATCHDOG_NOTICE);
    }
    // If Spamicide was on a login form: stop validating, quit the current request
    // and forward to the current page (like a reload) to prevent logging in.
    // We do that because the log in procedure, which happens after
    // spamicide_validate(), does not check error conditions of extra form
    // elements like the Spamicide.
    if ($form_id == 'user_login' || $form_id == 'user_login_block') {
      drupal_goto($_GET['q']);
    }
    else {
      drupal_goto($form_state['values']['#post']['destination']);
    }
  }
}


/**
 * Place the spamicide field just before the submit button
 * @param $form_id
 * @param $form
 */
function spamicide_pre_render_place_spamicide($form) {
  // search the weights of the buttons in the form
  $button_weights = array();
  foreach (element_children($form) as $key) {
    if ($key == 'buttons' || isset($form[$key]['#type']) && ($form[$key]['#type'] == 'submit')) {
      $button_weights[] = $form[$key]['#weight'];
    }
  }
  if ($button_weights) {
    // set the weight of the Spamicide element a tiny bit smaller than the lightest button weight
    // (note that the default resolution of #weight values is 1/1000 (see drupal/includes/form.inc))
    $first_button_weight = min($button_weights);
    $spamicide_field = _spamicide_get_field($form_id);
    if ($spamicide_field) {
      $form[$spamicide_field]['#weight'] = $first_button_weight - 0.5/1000.0;
    }
    else {
      $form['spamicide']['#weight'] = $first_button_weight - 0.5/1000.0;
    }
    // make sure the form gets sorted before rendering
    unset($form['#sorted']);
  }
  return $form;
}


/**
 * Get the spamicide field name and .css file_name
 * @param $form_id
 * @return the spamicide field name and .css file_name to call or FALSE
 */
function _spamicide_get_field($form_id) {
    $result = db_query("SELECT enabled, form_field FROM {spamicide} WHERE form_id = '%s'", $form_id);
    if ($result) {
      $spamicide = db_fetch_object($result);
      if ($spamicide->enabled) {
        return $spamicide->form_field;
      }
      else {
        return FALSE;
      }
    }
}


function _spamicide_set_css_file($form_field) {
  $css_file = 'spamicide/'. $form_field .'.css';
  $path = file_create_path($css_file);
  if (!file_exists($path)) { // or !is_file or !file_exists or !file_check_location
    $css = "#edit-". str_replace('_', '-', $form_field) ."-wrapper\n{\n  display: none;\n}\n";
    file_save_data($css, $css_file, FILE_EXISTS_REPLACE);
  }
}

/**
 * Show translation if available
 * @param $lang_code
 * @return translated field description
 */
function _spamicide_get_description($lang_code=NULL) { // work to be done
  $default = t('To prevent automated spam submissions leave this field empty.');
  if (module_exists('locale')) {
    if ($lang_code == NULL) {
      global $language;
      $lang_code = $language;
    }
    $description = variable_get("spamicide_description_$lang_code", $default);
  }
  else {
    $description = variable_get('spamicide_description', $default);
  }
  return $description;
}


