<?php
// $Id: editview_plugin_row_node_edit.inc,v 1.1 2009/02/17 00:39:02 agileware Exp $

/**
 * @file
 * Row style plug-in file.
 *
 * This is kept in a separate file and included only when needed to prevent
 * missing class errors.
 */

/**
 * @addtogroup editview
 * @{
 */

/**
 * Row plugin to allow node editing.
 *
 * Fields which are added to the view will be editable.
 */
class editview_plugin_row_node_edit extends views_plugin_row {
}

/**
 * @} End of "addtogroup editview".
 */
